#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"

cd $ROOT_DIR
rm -f build/zotero_connector-*.zip
web-ext build -s build/browserExt -a build
mv build/zotero_connector-*.zip build/zotero_connector_unsigned.xpi
echo "Extension moved to build/zotero_connector_unsigned.xpi"
