#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"
BUILD_DIR="$( cd "$ROOT_DIR"/build && pwd )"

. "$ROOT_DIR/config.sh"

rsync -a --delete "$BUILD_DIR/browserExt/" "$BUILD_DIR/firefox/"
cd "$BUILD_DIR/firefox/"

# Remove 'optional_permissions' property used by Chrome from the manifest.
# If we start using other optional permissions in Firefox before 'management'
# is supported in Firefox, we can probably get jq to delete just 'management'.
cat manifest.json | jq '. |= del(.optional_permissions)' > manifest.json-tmp
mv manifest.json-tmp manifest.json

