#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"
BUILD_DIR="$( cd "$DIR"/../../build && pwd )"

. "$ROOT_DIR/config.sh"

rm -f "$BUILD_DIR"/*.xpi
VERSION="$( cat "$BUILD_DIR/browserExt/manifest.json" | jq -r .version )"
echo "Signing $VERSION"
sleep 3
web-ext sign -s "$BUILD_DIR/browserExt" -a $BUILD_DIR -v
