#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"

. "$ROOT_DIR/init.sh"

if [ "$( ls "$BUILD_DIR"/*.safariextz | wc -l )" -gt 1 ]; then
	echo "More than one .safariextz found" >&2
	exit 1
fi

ls "$BUILD_DIR"/*.safariextz
