#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"
BUILD_DIR="$( cd "$ROOT_DIR"/build && pwd )"

rm -rf "$ROOT_DIR"/dist/Zotero_Connector*.zip

cd "$BUILD_DIR"
rsync -a --delete manifestv3/ edge/
cd edge

# Remove test file from web_accessibile_resources
jq 'del(.web_accessible_resources[0].resources[] | select(test("test/")))' manifest.json > manifest2.json
mv manifest2.json manifest.json

version=$(cat manifest.json | jq -r .version)
filename="Zotero_Connector-$version.zip"

zip -r ../$filename *
mv ../$filename "$ROOT_DIR/dist"

echo
echo "Built $ROOT_DIR/dist/$filename"
